### ISSUE TITLE
Not an issue but a request : Textile syntax on articles

### ISSUE THREAD

**Issue by jpdupont** [spiffin/spf_codemirror#3]
Hello !
This plugin is each time my first plugin installed, a must have !

What I need : codemirror give us Textile syntax . Is it difficult to setup spf_codemirror with Textile on the articles tab ?

Thanks !

Jean-Pol

**Comment by spiffin** [comment]
Hello. I'm afraid I don't see any benefit in applying Codemirror to the Write page. The two main reasons for the plugin are 1) code-completion (which isn't relevant with Textile) and 2) syntax highlighting (again not relevant). Textile is very easy to read as it is. Plus, there's a preview pane on the write page.

**Comment by jpdupont** [comment]
Hello Simon,

Not for me but for  my final user, I see  big benefits, in syntax 
highlighting.

Thanks again, for the code part of the plugin.

JP

Le 25/04/2015 19:12, Simon Finch a écrit :

> Hello. I'm afraid I don't see any benefit in applying Codemirror to 
> the Write page. The two main reasons for the plugin are 1) 
> code-completion (which isn't relevant with Textile) and 2) syntax 
> highlighting (again not relevant). Textile is very easy to read as it 
> is. Plus, there's a preview pane on the write page.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/spiffin/spf_codemirror/issues/3#issuecomment-96238863.

## 

Jean-Pol Dupont
ALYSSE SPRL
33, rue de Robivaux,
B-6760 VIRTON
0470 64 84 34 (modifié)
